### ISSUE TITLE
VPAID integration not working

### ISSUE THREAD

**Issue by rati592** [MailOnline/videojs-vast-vpaid#3] opened 2015-07-07 04:40 UTC
I am checking your example for VPAID ad but it is not working. Always it is saying timeout. Please let me know how can i check if VPAID ad is working with this plugin.

**Comment by Slotos** [comment] 2015-07-09 17:21
Have you tried increasing timeout? Certain ad networks are notoriously sloppy with how they handle ad loading, which may lead to AdStarted event firing quite late.

**Comment by edmetall** [comment] 2015-07-20 03:32
I've tried increase the timeout but still doesn't work, what can be the reason?

**Comment by Fetz** [comment] 2015-07-21 09:41
can you give me the link of the creative to test?

**Comment by orcaman** [comment] 2015-07-23 10:31
Hi,

Nice work.

I too can't get any "real" ad tags to work. Try these:
LiveRail test tag:
https://ad3.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2-vpaid

Brightroll test tag:
http://vast.bp3863356.btrll.com/vast/3863356?n=1426410433&br_w=300&br_h=250&br_pageurl=blah

Both work with JW Player / other implementations I'm looking at, but do not work when I test them out from your live demo page (http://mailonline.github.io/videojs-vast-vpaid/#).

**Comment by carpasse** [comment] 2015-07-23 11:41
@orcaman Thanks for the test links. We have been able to reproduce the issue and we are working to find the problem. 

We will keep you posted with our progress.

**Comment by Fetz** [comment] 2015-07-24 11:12
@orcaman we fixed the issues with the ad tags. You can test in demo page. Can we use your links in our demo page?

@edmetall check if this latest fix is fixing your issues you were having.

@rati592 check if this fix your issues.

The reason the ad's were failing, It was related with a 3rd party as3 code that I was using to load the ad's but some ad's for some reason they didn't like to be loaded that way. So removed that dependency.

**Comment by orcaman** [comment] 2015-07-26 07:44
@Fetz awesome. Yes, you can use them as far as I know (they do not "belong" to me as they are test tags by LiveRail and Brightroll).

**Comment by carpasse** [comment] 2015-07-27 09:06
@orcaman Thanks we will do so.

@orcaman, @edmetall, @rati592  can you please confirm that the issue is solved?
I would like to close the issue if possible.

**Comment by junaidtufail** [comment] 2015-07-27 19:38
@Fetz @carpasse 

these 2 tags are working fine on your demo site

https://ad3.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2-vpaid

Brightroll test tag:
http://vast.bp3863356.btrll.com/vast/3863356?n=1426410433&br_w=300&br_h=250&br_pageurl=blah

i have setup a page but these 2 tags are not working on below url.
http://wptester.info/vpaid/demo.html

in below url i get tag from your demo and its working

http://wptester.info/vpaid/demo1.html

please help me working liverail tag on below url

http://wptester.info/vpaid/demo.html

Thanks

**Comment by orcaman** [comment] 2015-07-27 19:49
Issue is resolved as far as I am concerned.

**Comment by junaidtufail** [comment] 2015-07-27 19:54
@orcaman do you have some your own demo url with minimal configuration i showed ?
It will help me a lot.

**Comment by Fetz** [comment] 2015-07-27 20:18
@junaidtufail I was checking your demo, you are missing swfobject, use this one [swfobject](https://github.com/swfobject/swfobject) or use the same we are using in [demo](https://github.com/MailOnline/videojs-vast-vpaid/blob/gh-pages/scripts/swfobject.js).
Don't forget that you will need https://github.com/MailOnline/videojs-vast-vpaid/blob/gh-pages/VPAIDFlash.swf

To help you can check the configuration we are using in the demo check here:
https://github.com/MailOnline/videojs-vast-vpaid/tree/gh-pages

@carpasse we should add in the bin to put the swfobject there (not minified), and fix the errors messages to be developer friendlier.

**Comment by junaidtufail** [comment] 2015-07-28 07:11
@Fetz  Thanks for your reply. It working great for me now. 

The only issue i have now is vast timeout error message sometimes.  How i can increase timeout or can fix this issue?

Thanks,

**Comment by carpasse** [comment] 2015-07-28 08:26
@Fetz I have added swfobject to the bin and modified the build so that it gets added on every release.

@junaidtufail You need to set the [adCancelTimeout option](https://github.com/MailOnline/videojs-vast-vpaid#adcanceltimeout)

Please go to the [integration with videojs](https://github.com/MailOnline/videojs-vast-vpaid#integration-with-videojs) section of the readme, in there you can find how to use that option.

**Closed by carpasse** 2015-07-28 08:26 UTC
Labels: bug

**Comment by adosia** [comment] 2015-09-03 13:28
Thanks guys for all your great work!
