### ISSUE TITLE
Specific VPAID not working (does work with jwplayer)

### ISSUE THREAD

**Issue by yonida** [MailOnline/videojs-vast-vpaid#40] opened 2015-09-02 13:37 UTC
I wanted to test some VPAID examples from `http://www.advertserve.com/blog/2013/08/mid-post-roll-video-ads/` and turn out the following url does not work:
`http://tester.advertserve.com/servlet/vast2/media?mid=123&pid=0&random=__random-number__#sthash.1Oe79f7T.dpuf`

It does work with jwplayer and flowplayer.
looks like the response returns, but the ad is not running.

**Comment by bkolo** [comment] 2015-09-02 14:07
It looks like the plugin is working correctly. The video (creative) the
vast response returns that the vpaid plugin can play is 2 GB in size.  It
think the issue is the file is too large and just times out.

**Comment by Fetz** [comment] 2015-09-02 14:07
Looks like that tag is VAST not VPAID (no apiFramework="VPAID", mediaFiles are flv and videos not swf or js).

**Comment by yonida** [comment] 2015-09-02 14:12
I don't think it's a timeout issue since the timeout error is not thrown.
I believe it has something to do with the file format.

**Comment by carpasse** [comment] 2015-09-02 14:55
It seams VideoJs is not handling well ads with delivery=streaming we need to filter the mediafiles to play video with progressive delivery

**Comment by carpasse** [comment] 2015-09-11 09:59
@yonida Did you try to play the ad on the flash jwplayer? 

I am asking you this because **there are some errors on the way the failing mediaFiles are being delivered to the player**. The response headers are wrong I think the problem is not on the plugin/videojs but in the way the adserver delivers them.

I have created an issue on videojs (https://github.com/videojs/video.js/issues/2580) explaining the issue with the sources to ensure that the problem is not the player but the srcs. 

 Do you have any other ad that returns mediafiles with "delivery:streaming" that we can test?? or can you reach the adprovider explaining the response header problems that I described in the videojs issue above and post here their response?

**Comment by yonida** [comment] 2015-09-11 10:23
@carpasse I tested the Ad in jwplayer ad tester page: http://demo.jwplayer.com/ad-tester/
The Ad url is just a url I found on the web. I didn't encounter any other Ads like that one.

**Comment by yonida** [comment] 2015-09-11 10:23
@carpasse I tested the Ad in jwplayer ad tester page: http://demo.jwplayer.com/ad-tester/
The Ad url is just a url I found on the web. I didn't encounter any other Ads like that one.

**Comment by carpasse** [comment] 2015-09-11 10:29
@yonida that player is indeed a flash player. I am going to wait to see what the guys from videojs answer. It may be a good Idea to ad a fallback from failing sources. It seams that videojs does not recover gracefully even though we provide more than one source.

**Comment by yonida** [comment] 2015-09-11 10:32
Great, lets wait to see what the guys from videojs say about this.

**Comment by carpasse** [comment] 2015-09-11 14:51
I did not realise that the extensions did not match the files real types. They pointed this out on the issue I created on videojs. 

There is no way the player can play that file unless the type of the mediafile matches the real type of the source. Therefore I am closing the issue because it is the ad that is wrong.

**Closed by carpasse** 2015-09-11 14:51 UTC
Labels: VAST

**Comment by yonida** [comment] 2015-09-11 14:54
@carpasse thank you for your time!

**Comment by carpasse** [comment] 2015-09-11 14:57
@yonida no worries thanks for adding the issue it may had been a problem
