### ISSUE TITLE
VPAID plugin show me an error message

### ISSUE THREAD

**Issue by edmetall** [MailOnline/videojs-vast-vpaid#4] opened 2015-07-20 16:49 UTC
Hi, I'm tried to play VPAID files but didn't work, it retirned an error message "VAST Error: on VPAIDAdUnitWrapper, the passed VPAI…Unit does not fully implement the VPAID interface". I'm tried with many VPAID files but it's the same message, What can be the problem?

**Comment by Fetz** [comment] 2015-07-21 09:49
HTML5/JS VPAID ad? or Flash VPAID? Can you give me the files/url you are using so will be easier to fix if is a problem with the plugin?

**Comment by carpasse** [comment] 2015-07-27 09:27
I am closing this issue since there has been no answer for the last 6 days. We did some fixes on the way we were loading the flash ads. 

@edmetall please check if the issue is solved and if not reopen the issue.

**Closed by carpasse** 2015-07-27 09:27 UTC
Labels: bug

**Comment by edmetall** [comment] 2015-07-29 01:43
It works with one of my VPAID samples, but with this doesn't works

http://shadowcdn-01.yumenetworks.com/ym/1B3uA91O2152/1349/HifvrHol/vpaid_as3.xml

**Comment by carpasse** [comment] 2015-07-29 08:02
The reason why your tag is not working is due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). The server is not setting the "Access-Control-Allow-Origin" header properly and the browser rejects the request. If you open the console you can see the error.

If you start chrome with the security disabled and load the tag in the demo you do see the ad. When I run it, I saw a land rover ad.

To start Chrome without security you need to:

1.- Close chrome open the terminal and type

For MacOs
```
$ open -a Google\ Chrome --args --disable-web-security
```
For Linux
```
$ google-chrome --disable-web-security
```

I don't know how to do it for window. sorry

Unfortunately there is nothing we can do from the plugin perspective. You need to contact your ad server and request them to set the  "Access-Control-Allow-Origin" accordingly.

We are experimenting the same problem with some of our ad providers and have requested the same thing.

In case you wonder why this problem doesn't happen with a flash player that is because flash doesn't do the request through the browser and it can bypass their security.

**Comment by Fetz** [comment] 2015-07-29 09:29
In mac OS:

I tested in Chrome before upgrading `43.0.2357.134 (64-bit)` and the latest `Version 44.0.2403.125 (64-bit)` and that tag is working.

In safari `8.0.7 (10600.7.12)` the tag is working as well (but I had to allow flash in the test page to work).

But in firefox is not working and there is not flag that I know to disable CORS.
