### ISSUE TITLE
Clickthrough event with HTML5 Vpaid

### ISSUE THREAD

**Issue by joshmadewell** [MailOnline/videojs-vast-vpaid#29] opened 2015-08-23 17:24 UTC
Using this plugin, if you click an add that is loaded using the HTML5Tech that nothing happens when a user clicks the ad.

I'm currently working on making a PR for this but wanted to make the issue known in the event that this is something you are all aware of.

HTML5 Liverail Example:
https://ad4.liverail.com/?LR_PUBLISHER_ID=1331&LR_SCHEMA=vast2-vpaid&LR_FORMAT=application/javascript

FLASH Liverail Example
https://ad4.liverail.com/?LR_PUBLISHER_ID=1331&LR_SCHEMA=vast2-vpaid

**Comment by Fetz** [comment] 2015-08-24 13:59
Hi @joshmadewell,

Yes we were informed about that issue by a publisher, but we didn't fix it yet.

Yes you can do a pull request.

Cheers

**Comment by joshmadewell** [comment] 2015-08-24 14:04
Alright, I'm actually working on a few things that we need at my job right now. Perhaps they are some other things you guys are working on?

1. Clickthru bug.
2. Ability to call setAdVolume/stopAd from the player.
3. Ad listening to player volume changes.

I'll make a PR for each individually if I'm able to fix them.

**Comment by Fetz** [comment] 2015-08-24 14:33
Regarding the point 2 and 3 that should be working...

**Comment by joshmadewell** [comment] 2015-08-24 14:37
I was both hoping and not hoping you'd say that.

I just went through and realized that volume controls are indeed happening. (I can change the volume using videojs controls, call getAdVolume and see that the ad is aware of the new volume). I wasn't sure because I never got an AdVolumeChanged event.

Regarding the stopAd...how exactly are we supposed to call stopAd manually? I didn't see a function exposed on the vast.adUnit so I assumed this wasn't coded for?

**Comment by Fetz** [comment] 2015-08-24 14:46
Maybe you are using the wrong event? It should be **AdVolumeChange** not *AdVolumeChanged*.

**Comment by joshmadewell** [comment] 2015-08-24 14:52
I just checked and I'm definitely listening to AdVolumeChange sorry for the confusion.

I had to go into the source code and add the emitters for the events, should these events already be getting emitted out to the browser?

**Comment by Fetz** [comment] 2015-08-24 15:13
Regarding the stopAd, yes we are not adding that. If you are interested on that, check the skipAd code in the VPAIDIntegrator, but you should only skip the ad when the ad is in a skippable state...

Regarding the ad volume if we aren't emitting, you can add it, but you still can get the volume change using the normal player event **volumechange**

**Comment by joshmadewell** [comment] 2015-08-25 01:39
@Fetz 

Hey, I just wanted to reach out to you about the clickthru bug that this issue was made for.

I'm trying my best to go through and find out why this isn't happening but do you know if there is supposed to be some IAB method that exists on a vpaid ad that we're suppose to call when the user clicks? I've gone through a lot of VPAID documentation and for the life of me I can't find anything...

**Comment by Fetz** [comment] 2015-08-25 13:15
I will let you know when is fixed

**Comment by Fetz** [comment] 2015-08-25 13:44
@joshmadewell the fix is not simply fixing the css. To fix it correctly we need to ad the element that is being used outside of the iframe, but the problem is that we found that some ads were messing up the css of the page because they weren't prefixing the css that they were loading... I will check how I can still avoid that and still enable the clickthru

**Comment by Fetz** [comment] 2015-08-25 14:46
this issue will be fixed in the next release

**Comment by Fetz** [comment] 2015-08-26 12:20
I updated the demo page with the fix for the clickthru.

http://mailonline.github.io/videojs-vast-vpaid

**Comment by Fetz** [comment] 2015-08-28 13:04
The fix is done, if there is still an issue please reopen this issue

**Closed by Fetz** 2015-08-28 13:04 UTC
Labels: bug
