### ISSUE TITLE
Credentials flag

### ISSUE THREAD

**Issue by zillionn** [MailOnline/videojs-vast-vpaid#90] opened 2015-10-30 19:19 UTC
Hello,

I'm getting the following browser error:
XMLHttpRequest cannot load http://... A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://...' is therefore not allowed access.

Do I need to set somewhere "withCredentials" to false or the problem is with the ad server?

Thanks.

**Comment by indieveed** [comment] 2015-11-05 10:47
Experience the same issue. Seems like withCredentials is always set to "true".

**Comment by Valentin1918** [comment] 2015-11-09 12:00
So what to do in this case?

**Comment by indieveed** [comment] 2015-11-16 12:56
I have example VAST XML for this case. It is not playing on demo page:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<VAST version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd">
	<Ad id="1467224">
		<Wrapper>
			<AdSystem version="1.0">afx</AdSystem>
			<!--AdTitle>VAST Wrapper Ad</AdTitle-->
			<VASTAdTagURI><![CDATA[http://mars.solution.weborama.fr/fcgi-bin/dispatch.fcgi?a.A=im&a.si=61&a.te=3436&a.he=1&a.wi=1&a.hr=X&a.ra=897536662&a.ycp=co:100|st:0]]></VASTAdTagURI>
<Impression><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=fdlriet&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=3dcb64b34834149c&pm=b&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Impression>
<Impression><![CDATA[]]></Impression>
<Impression><![CDATA[]]></Impression>
			<Creatives>
				<Creative id="1467224/520056">
					<Linear>
						<TrackingEvents>
<Tracking event="creativeView"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=blsvwvq&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=c6e3ec65c3665f42&pm=c&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="start"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=giggdzw&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=37ea3ef46dfaa687&pm=d&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="midpoint"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=noeomf&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=69d53b89f29a3ced&pm=f&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="firstQuartile"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=bmhopko&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=68c7af7903f3e311&pm=e&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="thirdQuartile"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=mrkgxl&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=36816458245ecd8f&pm=g&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="complete"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=xncsel&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=4e23dcb2237ce2a4&pm=h&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="mute"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=bjujemx&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=5dcbf08f039f51db&pm=i&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="unmute"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=fbkgjrf&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=f82fce4ec997dcfa&pm=j&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="pause"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=eqiozci&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=c11c9caf26ed247b&pm=k&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="rewind"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=ffttebj&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=91ea1e46f67a477f&pm=l&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="resume"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=ctvrkeq&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=95df59332784d244&pm=m&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="fullscreen"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=ccmbivj&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=43e47bf31c1f581e&pm=n&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="expand"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=enezkur&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=40e577ea7e75948f&pm=o&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="collapse"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=cleiygr&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=26753805dc93b726&pm=p&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="acceptInvitation"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=fexmqpr&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=21d21b4fad33a0db&pm=q&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>
<Tracking event="close"><![CDATA[http://v.adfox.ru/226279/event?p2=eyit&rand=gqivddk&p5=dfmls&p1=bofrw&pr=`&puid6=1&lts=ervyrqa&puid30=2530&hash=ef07a08013dabd44&pm=r&eid1=2530:14476767245931096568092:25301447676724593151236209]]></Tracking>

						</TrackingEvents>
<VideoClicks>
<ClickTracking><![CDATA[http://v.adfox.ru/226279/goLink?eid1=2530:14476767245931096568092:25301447676724593151236209&puid30=2530&puid6=1&pr=cxocayw&p5=dfmls&p1=bofrw&p2=eyit@]]></ClickTracking>
</VideoClicks>
					</Linear>
				</Creative>
			</Creatives>
<Extensions>
<Extension type="Urlmod" scope="" method="" final="false">
<urlpart><![CDATA[]]></urlpart>
</Extension>
<Extension type="CustomTracking">
                    <Tracking event="onVastLoad"><![CDATA[http://www.tns-counter.ru/V13a****vitpc_ad/ru/CP1251/tmsec=vitpc_monitoring-1/897536662]]></Tracking>
                </Extension>
<Extension type="skipTime2"><![CDATA[00:05]]></Extension>
<Extension type="controls"><control id="adlabel" layout="0"/>
<control id="countdown" layout="0"/><control id="soundbtn" layout="0"/></Extension>
</Extensions> 
		</Wrapper>
	</Ad>
</VAST>
```

**Comment by indieveed** [comment] 2015-11-16 13:28
I think that we need to have an option to set "withCredentials" parameter outside of the lib code

**Comment by indieveed** [comment] 2015-11-24 09:55
Seems like the same problem as in #92

**Comment by Fetz** [comment] 2015-12-04 11:05
We have to set withCredentials if not we will have issues with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) in some browsers (Firefox) and more browsers in the future.

https://github.com/MailOnline/videojs-vast-vpaid/issues/46

**Comment by indieveed** [comment] 2015-12-04 11:09
It seems like the problem is on your ads' provider side. Try to communicate with them on this issue. In this case provider should set 'Access-Control-Allow-Origin' header to your domain. We could solve this issue with our provider.

**Comment by Fetz** [comment] 2016-01-05 10:19
Closing this issue, since there isn't anymore feedback

**Closed by Fetz** 2016-01-05 10:19 UTC
